version: "3.8"

services:
  database:
    build:
        context: ../..
        dockerfile: ./docker.d/dockerfiles/mysql.Dockerfile
    container_name: $COMPOSE_PROJECT_NAME-mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - $PWD/run/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
    ports:
      - '3306:3306'
    networks:
      - backend

secrets:
  db_root_password:
    file: ../secrets/mysql/db_root_password