version: "3.8"

services:
  database:
    build:
        context: ../..
        dockerfile: ./docker.d/dockerfiles/mysql.Dockerfile
    container_name: $COMPOSE_PROJECT_NAME-mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /opt/$COMPOSE_PROJECT_NAME/mysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sqlPractice
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    networks:
      - backend